name: Generate changelog and bump the version
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'What kind of release is this?'
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  version:
    permissions:
      id-token: write
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout the repository
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node and Git
        uses: ./.github/actions/setup-node-and-git

      - name: Generate the changelog
        id: generate-changelog
        run: |
          echo "test"

      - name: Bump version
        shell: bash
        run: |
          npm version ${{github.event.inputs.releaseType}}
